### ISSUE TITLE
Github callback URL should be configurable in a json file

### ISSUE THREAD

**Issue by MagicMicky** [Whalee/whalee-webapp#1]
On devrait pouvoir configurer l'url de callback de github depuis un fichier Github. Pour ce faire : 
- Créer un fichier `config.json` a la racine du projet, avec dedans: 

``` json
{
  "callbackurl":"http://localhost:3000",
}
```
- Ajouter un fichier de template `config.json.template` a la racine, contenant la template du json attendu dans le `config.json`
- Ajouter `config.json` au gitignore

Dans votre fichier server.js : 
- Ajouter un `var config = require("./config.json");`
- Utiliser `config.callbackurl` en lieu et place du callback hardcodé

**Comment by femtozer** [comment]
C'est corrigé. 
Tu peux trouver config.json.template dans le dossier config
